/* SPDX-License-Identifier: GPL-2.0 */
/* Generated by kernel/scripts/isp/gen-ccm.py. Do not edit. */
/*
 * CCM register-bank init blocks, 20 words each: ccm1 at ISP +0x3400 (an
 * identity matrix pair) and ccm2 at +0x3800 (the vendor's fixed matrix
 * pair), lifted verbatim from the vendor service's ISP-init template.
 * The ccm2 block is word-identical to the traced init writes; the ccm1
 * block decodes to an identity under the packing in ar-isp-colour.h.
 */

#ifndef AR_ISP_CCM_INIT_H
#define AR_ISP_CCM_INIT_H

static const u32 ar_isp_ccm1_init[20] = {
	0x00000100, 0x00000000, 0x01000000, 0x00000000,
	0x00000000, 0x00000100, 0x00000000, 0x00000000,
	0x00000100, 0x00000000, 0x01000000, 0x00000000,
	0x00000000, 0x00000100, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
};

static const u32 ar_isp_ccm2_init[20] = {
	0x80f7020c, 0x00008017, 0x01978051, 0x00008048,
	0x80868003, 0x00000187, 0x00000000, 0x00000000,
	0x80f7020c, 0x00008017, 0x01978051, 0x00008048,
	0x80868003, 0x00000187, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
};

#endif /* AR_ISP_CCM_INIT_H */
