/* SPDX-License-Identifier: GPL-2.0 */
/* Generated by kernel/scripts/gen-ccm.py. Do not edit. */
/*
 * CCM register-bank init blocks, 20 words each for ISP +0x3400 (ccm1,
 * an identity matrix pair) and +0x3800 (ccm2, the vendor's fixed matrix
 * pair). Lifted from ISP-init template entries 33 and 34 of the vendor
 * service library; the ccm2 block is word-identical to the registers the
 * vendor was traced writing, and the ccm1 block decodes to an identity
 * under the packing in ar-isp-colour.h.
 *
 * Source library sha256 4cfc8e6cfb42d8c821137993b95b152f1aaad7c53ce425e6a0493c4dd453936c.
 * Tuning file sha256 33fb86da0dc17a8c38570dbf3a13b6ef1bfe64a736560f47a03dc3f3cb5582b5.
 */

#ifndef AR_ISP_CCM_INIT_H
#define AR_ISP_CCM_INIT_H

static const u32 ar_isp_ccm1_init[20] = {
	0x00000100, 0x00000000, 0x01000000, 0x00000000,
	0x00000000, 0x00000100, 0x00000000, 0x00000000,
	0x00000100, 0x00000000, 0x01000000, 0x00000000,
	0x00000000, 0x00000100, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
};

static const u32 ar_isp_ccm2_init[20] = {
	0x80f7020c, 0x00008017, 0x01978051, 0x00008048,
	0x80868003, 0x00000187, 0x00000000, 0x00000000,
	0x80f7020c, 0x00008017, 0x01978051, 0x00008048,
	0x80868003, 0x00000187, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
};

#endif /* AR_ISP_CCM_INIT_H */
