# SPDX-License-Identifier: GPL-2.0

obj-$(CONFIG_VIDEO_ARTOSYN_NT99235) += nt99235.o
obj-$(CONFIG_VIDEO_ARTOSYN_CSI2) += ar-csi2.o
obj-$(CONFIG_VIDEO_ARTOSYN_VIF) += ar-vif.o
obj-$(CONFIG_VIDEO_ARTOSYN_ISP) += ar-isp.o
