"""
Vendor-image helpers shared by the ISP generator and checker scripts.

Covers the two structures every script that reads libmpp_service.so needs: the
VMA-to-file mapping, and the ISP-init template array, plus the header envelope
every generator wraps its tables in. Nothing here parses an MMIO trace.
"""

import struct
import sys
from collections.abc import Sequence

# The second LOAD segment maps file 0x4004d0 at 0x4104d0. Every VMA this tree
# quotes is in that segment, so VMA - 0x10000 is its file offset.
VMA_TO_FILE = 0x10000

# ISP-init template array: the contiguous {u64 source, u64 length} descriptor
# list the service copies its static payloads from. See
# docs/camera-isp-recovery.md.
#
# The library carries one array per SoC in the family, reached by name through
# the registry in .__ar_app_list__list: ar9341_isp_init_hw_opt returns 0x472600,
# ar9311_isp_init_hw_opt returns this one, ar9411_isp_init_hw_opt returns
# 0x4a9c00. This device is an AR9311, so the ar9311 array is the one that
# applies. Thirteen of the 76 entries differ between the three, and the array
# ends where the ops object it belongs to begins, at +0x4c0.
TEMPLATE_ARRAY_VMA = 0x48C770
TEMPLATE_ENTRIES = 76
TEMPLATE_ENTRY_BYTES = 16


def lib_slice(lib: bytes, vma: int, length: int, what: str) -> bytes:
    """
    `length` bytes of `lib` at `vma`, or exit naming `what`.

    Python truncates an out-of-range slice silently, so the bounds are checked
    here rather than left to the caller's unpack.
    """
    off = vma - VMA_TO_FILE
    if off < 0 or off + length > len(lib):
        sys.exit(f"{what}: VMA 0x{vma:x} + 0x{length:x} lies outside the library")

    return lib[off:off + length]


def template_entry(lib: bytes, index: int,
                   source: str | None = None) -> tuple[int, int]:
    """
    (source VMA, length) of one ISP-init template descriptor.

    `source` prefixes any error, for callers that accept more than one file.
    """
    where = f"{source}: " if source else ""
    if not 0 <= index < TEMPLATE_ENTRIES:
        sys.exit(f"{where}template entry {index} is outside the "
                 f"{TEMPLATE_ENTRIES}-entry array")

    raw = lib_slice(lib, TEMPLATE_ARRAY_VMA + index * TEMPLATE_ENTRY_BYTES,
                    TEMPLATE_ENTRY_BYTES, f"{where}template array entry {index}")

    return struct.unpack("<QQ", raw)


def template_payload(lib: bytes, index: int, expect_length: int,
                     source: str | None = None) -> bytes:
    """
    The bytes one template descriptor points at, its length asserted.

    A length mismatch means the array layout moved, which is what the callers
    exist to catch, so it exits rather than returning a short payload.
    """
    where = f"{source}: " if source else ""
    src, length = template_entry(lib, index, source)
    if length != expect_length:
        sys.exit(f"{where}template entry {index} is 0x{length:x} bytes, expected "
                 f"0x{expect_length:x}; the array layout has changed")

    return lib_slice(lib, src, length, f"{where}template entry {index} payload")


# The header envelope. Each of these returns text rather than printing it, because the
# generators split between print() to stdout and write() to a -o file, and a returned
# string suits both without either growing a writer argument.


def banner(script: str, description: Sequence[str]) -> str:
    """
    The SPDX tag, provenance line and description block a generated header opens with.

    `script` is the generator's path as it should read in the header. `description`
    holds the block comment's lines without their " * " prefix; an empty string
    becomes the bare " *" separator.
    """
    lines = ["/* SPDX-License-Identifier: GPL-2.0 */",
             f"/* Generated by {script}. Do not edit. */",
             "/*"]
    lines += [f" * {line}" if line else " *" for line in description]
    lines.append(" */")

    return "\n".join(lines) + "\n"


def guard(macro: str) -> tuple[str, str]:
    """The opening and closing halves of an include guard, in that order."""
    return f"#ifndef {macro}\n#define {macro}\n", f"#endif /* {macro} */\n"


def rows(values: Sequence[int], per_line: int, spec: str,
         indent: str = "\t") -> str:
    """
    `values` as C initialiser rows, `per_line` values to a line.

    `spec` is a format spec for one value, so "#010x" for a 32-bit register word and
    "4d" for a right-aligned decimal sample. The trailing comma on the last row is
    kept: every caller emits these inside braces where C allows it.
    """
    lines = []
    for i in range(0, len(values), per_line):
        lines.append(indent + ", ".join(format(v, spec)
                                        for v in values[i:i + per_line]) + ",")

    return "\n".join(lines) + "\n"
