#!/usr/bin/env python3
"""
Generate the rgb2yuv colour-space matrices the vendor library carries.

isp_rgb2yuv_set_csc (0x19e528) picks one of four static float matrices in
libmpp_service.so and hands it to a writer at 0x19e318, which packs each
coefficient as sign-magnitude Q10: the magnitude is |coeff| * 1024 truncated
toward zero and bit 15 is the sign. The writer's negative path computes
32768.0f - coeff * 1024.0f, which is the same encoding written as an offset.

The four are the textbook set, BT.601 and BT.709 at full and limited range.
The shipped bank is BT.601 full range, and all six of its registers reproduce
bit-exactly against a streaming-vendor capture.

Register pairing, two coefficients per word, from the measured bank:

    0x3c00  Y.G  << 16 | Y.R
    0x3c04                Y.B
    0x3c08  Cb.G << 16 | Cb.R
    0x3c0c  Cr.R << 16 | Cb.B
    0x3c10  Cr.G << 16 | Cb.B
    0x3c14  Cb.B << 16 | Cr.B

Three fields hold the same value in every matrix, because Cb.B and Cr.R are
equal in all four (0.500, 0.511, 0.439, 0.439). Which of the two the hardware
reads at 0x3c0c high, 0x3c10 low and 0x3c14 high is therefore not decidable
from the data, and cannot matter: any assignment among equal values emits the
same word. Cb.B is used throughout and --check proves the result against the
capture for the shipped matrix.

    kernel/scripts/isp/gen-rgb2yuv.py \\
        --lib out/air-gather/vendor-root/usr/lib/libmpp_service.so \\
        > overlay/drivers/media/artosyn/vendor-tables/ar-isp-rgb2yuv.h
"""

import argparse
import importlib.util
import struct
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent

BANK = 0x3C00

# The four matrices, by the address the library holds them at. Names are from
# the coefficients themselves: 0.299/0.587/0.114 is BT.601, 0.213/0.715/0.072
# is BT.709, and the smaller pairs are their limited-range forms.
MATRICES = (
    ('bt601_full', 0x445CA0),
    ('bt709_full', 0x445CD0),
    ('bt601_limited', 0x445D10),
    ('bt709_limited', 0x445D40),
)

# The one the vendor ships, measured on a streaming unit.
DEFAULT = 'bt601_full'

# The shipped bank, from out/au-chain-slota-live. --check compares against it,
# so the generator cannot quietly stop reproducing the vendor.
MEASURED = (0x02590132, 0x00000074, 0x815280AD,
            0x02000200, 0x81AD0200, 0x02008052)


def load_gates():
    spec = importlib.util.spec_from_file_location('isp_gates',
                                                  HERE / 'isp-gates.py')
    mod = importlib.util.module_from_spec(spec)
    sys.modules['isp_gates'] = mod
    spec.loader.exec_module(mod)

    return mod


def read(lib, vma, n):
    """`n` bytes at a virtual address, through the program headers."""
    for lo, hi, delta in lib.segments:
        if lo <= vma < hi:
            return lib.data[vma + delta:vma + delta + n]

    sys.exit(f'0x{vma:x} is outside every loadable segment')


def field(value):
    """One coefficient as the writer emits it: Q10 magnitude, bit 15 the sign."""
    magnitude = int(abs(value) * 1024.0)
    if magnitude > 0x7FFF:
        sys.exit(f'coefficient {value} does not fit the 15-bit magnitude')

    return (0x8000 | magnitude) if value < 0 else magnitude


def pack(coeffs):
    """The six bank registers for one matrix."""
    y_r, y_g, y_b, cb_r, cb_g, cb_b, cr_r, cr_g, cr_b = (field(c)
                                                         for c in coeffs)
    del cr_r      # equal to cb_b in every matrix; see the module docstring

    return (
        (y_g << 16) | y_r,
        y_b,
        (cb_g << 16) | cb_r,
        (cb_b << 16) | cb_b,
        (cr_g << 16) | cb_b,
        (cb_b << 16) | cr_b,
    )


def main():
    ap = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument('--lib', required=True, help='libmpp_service.so')
    ap.add_argument('--check', action='store_true',
                    help='verify against the measured bank and print nothing')
    args = ap.parse_args()

    g = load_gates()
    lib = g.Library(args.lib)

    packed = {}
    for name, addr in MATRICES:
        coeffs = struct.unpack('<9f', read(lib, addr, 36))
        packed[name] = (coeffs, pack(coeffs))

    if packed[DEFAULT][1] != MEASURED:
        got = ' '.join(f'{v:08x}' for v in packed[DEFAULT][1])
        want = ' '.join(f'{v:08x}' for v in MEASURED)
        sys.exit(f'{DEFAULT} does not reproduce the vendor bank\n'
                 f'  generated {got}\n  measured  {want}')

    if args.check:
        print(f'{DEFAULT} reproduces all {len(MEASURED)} measured registers',
              file=sys.stderr)
        return 0

    out = ['/* SPDX-License-Identifier: GPL-2.0 */',
           '/* Generated by kernel/scripts/isp/gen-rgb2yuv.py. Do not edit. */',
           '/*',
           ' * The colour-space matrices the vendor library carries, packed for the',
           ' * rgb2yuv bank.',
           ' *',
           ' * isp_rgb2yuv_set_csc selects one of these four and a writer at 0x19e318',
           ' * packs it as sign-magnitude Q10: magnitude |coeff| * 1024 truncated, bit 15',
           ' * the sign. The shipped bank is BT.601 full range and reproduces bit-exactly',
           ' * against a streaming-vendor capture, which is what gen-rgb2yuv.py --check',
           ' * asserts.',
           ' *',
           ' * Full range puts black at 0 and white at 255; limited range puts them at 16',
           ' * and 235. Changing which matrix is applied is the levels lever for the whole',
           ' * YUV path, so the alternatives are carried rather than dropped.',
           ' */',
           '',
           '#ifndef AR_ISP_RGB2YUV_H',
           '#define AR_ISP_RGB2YUV_H',
           '',
           f'#define AR_ISP_RGB2YUV_BANK\t\t0x{BANK:04x}',
           f'#define AR_ISP_RGB2YUV_REGS\t\t{len(MEASURED)}',
           '',
           'struct ar_isp_csc {',
           '\tconst char *name;',
           f'\tu32 regs[{len(MEASURED)}];',
           '};',
           '']

    out.append('static const struct ar_isp_csc ar_isp_csc_matrices[] = {')
    for name, _addr in MATRICES:
        coeffs, regs = packed[name]
        rows = ', '.join(f'0x{v:08x}' for v in regs)
        out.append(f'\t/* {" ".join(f"{c:+.3f}" for c in coeffs)} */')
        out.append(f'\t{{ "{name}", {{ {rows} }} }},')
    out.append('};')
    out.append('')
    out.append('/* The matrix measured on the streaming vendor. */')
    out.append(f'#define AR_ISP_CSC_DEFAULT\t\t'
               f'{[n for n, _ in MATRICES].index(DEFAULT)}')
    out.append('')
    out.append('#endif /* AR_ISP_RGB2YUV_H */')

    print('\n'.join(out))

    return 0


if __name__ == '__main__':
    sys.exit(main())
