#!/usr/bin/env python3
"""
Emit ar-isp-blob.h, the driver's tuning-blob offsets, from blob-layout.toml.

Macro names come from the layout's [c_names] and [c_fields] tables, not from section names.

    kernel/scripts/isp/gen-blob-header.py --check     compare against the tree, exit 1 on drift
    kernel/scripts/isp/gen-blob-header.py --write     write the header
"""

import argparse
import pathlib
import re
import sys
import tomllib

HERE = pathlib.Path(__file__).resolve().parent
LAYOUT = HERE / "blob-layout.toml"
DRIVER = HERE.parents[1] / "overlay" / "drivers" / "media" / "artosyn"
OUT = DRIVER / "vendor-tables" / "ar-isp-blob.h"
USERSPACE_OUT = HERE.parents[2] / "userspace" / "ml-aed" / "ml-aed-blob.h"

# The stages ml-aed reads.
USERSPACE_STAGES = ("ae",)

Macros = dict[str, tuple[int, str]]


def load() -> dict:
    return tomllib.loads(LAYOUT.read_text())


def macros(doc: dict) -> Macros:
    """Every macro the header should define, as name -> (value, provenance).

    Two sections may claim one name when they share a value, as the ladder header words do.
    Disagreeing values are an error.
    """
    sections = {s["name"]: s for s in doc["section"]}
    out: Macros = {}

    def put(name: str, value: int, why: str) -> None:
        if name in out and out[name][0] != value:
            sys.exit(f"{name}: {out[name][0]:#x} from {out[name][1]} but {value:#x} from {why}")

        out.setdefault(name, (value, why))

    for section_name, names in doc.get("c_names", {}).items():
        if section_name not in sections:
            sys.exit(f"c_names references unknown section {section_name!r}")

        section = sections[section_name]
        for key, macro in names.items():
            if key == "offset":
                put(macro, section["offset"], section_name)
            elif key in ("stride", "count"):
                if key not in section:
                    sys.exit(f"{section_name} has no {key} for {macro}")

                put(macro, section[key], section_name)
            else:
                sys.exit(f"{section_name}: unknown c_names key {key!r}")

    for section_name, fields in doc.get("c_fields", {}).items():
        section = sections[section_name]
        for field, macro in fields.items():
            put(macro, section["fields"][field], f"{section_name}.{field}")

    for section_name, fields in doc.get("c_absolute_fields", {}).items():
        section = sections[section_name]
        for field, macro in fields.items():
            put(macro, section["offset"] + section["fields"][field],
                f"{section_name}+{field}")

    return out


def current() -> dict[str, int]:
    """What the driver's headers define outside the generated one."""
    found: dict[str, int] = {}
    for header in list(DRIVER.glob("*.h")) + list((DRIVER / "vendor-tables").glob("*.h")):
        if header.resolve() == OUT.resolve():
            continue

        for name, value in re.findall(
            r"#define\s+(AR_ISP_\w+)\s+(0x[0-9a-fA-F]+|\d+)\b", header.read_text()
        ):
            found[name] = int(value, 0)

    return found


def render(doc: dict, out: Macros) -> str:
    sections = {s["name"]: s for s in doc["section"]}
    width = max(len(n) for n in out) + 1

    lines = [
        "/* SPDX-License-Identifier: GPL-2.0 */",
        "/* Generated by kernel/scripts/isp/gen-blob-header.py. Do not edit. */",
        "/*",
        " * Where each tuning-blob field lives. Source: kernel/scripts/isp/blob-layout.toml.",
        " *",
        " * _BLOB_ names are absolute offsets in the file. _HDR_ names are displacements within",
        " * their header: AR_ISP_RNR_BLOB_HEADER + AR_ISP_RNR_HDR_MODE is 0x79e0.",
        " */",
        "#ifndef AR_ISP_BLOB_H",
        "#define AR_ISP_BLOB_H",
        "",
        f"#define AR_ISP_TUNING_SIZE\t\t{doc['meta']['size']:#x}",
        "",
    ]

    by_section: dict[str, list[str]] = {}
    for name, (_value, why) in out.items():
        by_section.setdefault(why.split(".")[0].split("+")[0], []).append(name)

    for section_name in sorted(by_section, key=lambda s: sections[s]["offset"]):
        section = sections[section_name]
        if section.get("doc"):
            lines.append(f"/* {section_name}: {section['doc']} */")
        else:
            lines.append(f"/* {section_name} */")

        for name in sorted(by_section[section_name], key=lambda n: out[n][0]):
            lines.append(f"#define {name:<{width}}{out[name][0]:#x}")

        lines.append("")

    lines += ["#endif /* AR_ISP_BLOB_H */", ""]

    return "\n".join(lines)


def render_userspace(doc: dict) -> str:
    """The AE offsets, for ml-aed in the userspace repo. tests/test_blob_layout.py checks drift."""
    ae = [s for s in doc["section"] if s.get("stage") in USERSPACE_STAGES]

    def base_of(section: dict) -> str:
        return f"MLAED_{section['name'].upper().removeprefix('AE_')}"

    # Widest emitted macro, suffix included.
    width = max(len(base_of(s)) + len(suffix)
                for s in ae for suffix in ("_OFF", "_COUNT", "_STRIDE")) + 1

    lines = [
        "/* Generated by kernel/scripts/isp/gen-blob-header.py --userspace. Do not edit. */",
        "/*",
        " * Where ml-aed's constants live in the sensor tuning blob.",
        " *",
        " * Source: kernel/scripts/isp/blob-layout.toml in the kernel repo, the same file the ISP",
        " * driver's offsets are generated from. The layout is identical for every sensor the",
        " * vendor ships; which file to load is a board fact and arrives via --tuning.",
        " */",
        "#ifndef ML_AED_BLOB_H",
        "#define ML_AED_BLOB_H",
        "",
        f"#define {'MLAED_TUNING_SIZE':<{width}}{doc['meta']['size']:#x}u",
        "",
    ]

    for s in sorted(ae, key=lambda s: s["offset"]):
        if s.get("doc"):
            lines.append(f"/* {s['doc']} */")

        base = base_of(s)
        lines.append(f"#define {base + '_OFF':<{width}}{s['offset']:#x}u")
        if s.get("count"):
            lines.append(f"#define {base + '_COUNT':<{width}}{s['count']}u")

        if s.get("stride"):
            lines.append(f"#define {base + '_STRIDE':<{width}}{s['stride']}u")

        lines.append("")

    lines += ["#endif /* ML_AED_BLOB_H */", ""]

    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true",
                    help="compare every macro against the driver's current headers")
    ap.add_argument("--write", action="store_true", help="write the header")
    ap.add_argument("--userspace", action="store_true",
                    help="also write userspace/ml-aed/ml-aed-blob.h")
    args = ap.parse_args()

    doc = load()
    out = macros(doc)

    if args.userspace:
        text = render_userspace(doc)
        if args.check:
            if not USERSPACE_OUT.exists() or USERSPACE_OUT.read_text() != text:
                print(f"{USERSPACE_OUT} differs from the layout. Regenerate it.")

                return 1

            print(f"{USERSPACE_OUT.name} matches the layout")

            return 0

        USERSPACE_OUT.parent.mkdir(parents=True, exist_ok=True)
        USERSPACE_OUT.write_text(text)
        print(f"{USERSPACE_OUT}")

        return 0

    if args.check:
        text = render(doc, out)
        if not OUT.exists():
            print(f"{OUT}: absent; run with --write")

            return 1

        if OUT.read_text() != text:
            print(f"{OUT} differs from what blob-layout.toml generates. Regenerate it.")

            return 1

        duplicated = sorted(n for n in current() if n in out)
        if duplicated:
            print("defined outside the generated header as well: " + ", ".join(duplicated))

            return 1

        print(f"{len(out)} macros, header matches the layout and nothing redefines them")

        return 0

    text = render(doc, out)
    if args.write:
        OUT.write_text(text)
        print(f"{OUT}: {len(out)} macros")
    else:
        sys.stdout.write(text)

    return 0


if __name__ == "__main__":
    sys.exit(main())
