#!/usr/bin/env python3
"""
Extract the static half of the Artosyn ISP's DRC page and emit it as a kernel header.

The DRC DMA page is 0x2000 bytes of four 257-sample curves. The first two are
rebuilt from the tuning file on every AE update and are generated at runtime by
ar-isp-codec.h. The second two are never recomputed: they are a prepacked
constant in the vendor service library, reached through the ISP-init descriptor
array as {source 0x467460, length 0x2000}, and the runtime writes only the first
half of what that descriptor loaded.

The curves are not present in the tuning file, in packed or unpacked form, so
they cannot be derived and have to be carried. They are emitted decoded, as
sample arrays rather than packed bytes, because the packing is already in
ar-isp-codec.h and a curve is reviewable where a blob is not.

The library is proprietary and not in the repository; supply it with --lib. The
generated header is checked in, so this script is rerun only if the vendor
library changes.

    kernel/scripts/gen-drc-tail.py --lib out/air-gather/vendor-root/usr/lib/libmpp_service.so \\
        > overlay/drivers/media/artosyn/ar-isp-drc-tail.h
"""

import argparse
import struct
import sys

# Second LOAD segment maps file 0x4004d0 at 0x4104d0, so VMA - 0x10000 is the
# file offset for everything in it.
VMA_TO_FILE = 0x10000

TEMPLATE_VMA = 0x467460
TEMPLATE_LEN = 0x2000

BANK = 0x800
RECORDS = 128
SAMPLES = 257
LANE_MAX = (1 << 20) - 1


def decode_bank(data, base):
    """Undo the packing in ar-isp-codec.h: 128 records, three overlapping 20-bit lanes."""
    samples = []
    for record in range(RECORDS):
        offset = base + record * 16
        word0, word1 = struct.unpack_from("<II", data, offset)
        half = struct.unpack_from("<H", data, offset + 8)[0]
        lane0 = word0 & LANE_MAX
        lane1 = ((word0 >> 20) & 0xFFF) | ((word1 & 0xFF) << 12)
        lane2 = ((word1 >> 28) & 0xF) | (half << 4)
        duplicate = (word1 >> 8) & LANE_MAX
        if lane1 != duplicate:
            sys.exit(f"record {record} at 0x{base:x}: overlap 0x{lane1:x} != 0x{duplicate:x}")

        if record == 0:
            samples.extend((lane0, lane1, lane2))
            continue

        if lane0 != samples[-1]:
            sys.exit(f"record {record} at 0x{base:x}: curve break 0x{lane0:x} != 0x{samples[-1]:x}")

        samples.extend((lane1, lane2))

    if len(samples) != SAMPLES:
        sys.exit(f"decoded {len(samples)} samples, expected {SAMPLES}")

    return samples


def emit(banks):
    print("/* SPDX-License-Identifier: GPL-2.0 */")
    print("/* Generated by kernel/scripts/gen-drc-tail.py. Do not edit. */")
    print("/*")
    print(" * The half of the DRC page the vendor never recomputes.")
    print(" *")
    print(" * Two 257-sample curves, decoded out of the prepacked 0x2000 template the vendor")
    print(" * service library loads through its ISP-init descriptor array. Neither curve appears")
    print(" * in the tuning file in any form, so unlike the first two banks they cannot be")
    print(" * generated and are carried here instead.")
    print(" */")
    print()
    print("#ifndef AR_ISP_DRC_TAIL_H")
    print("#define AR_ISP_DRC_TAIL_H")
    for n, samples in enumerate(banks):
        print()
        print(f"static const u32 ar_isp_drc_tail_bank{n}[AR_ISP_DRC_SAMPLES] = {{")
        for i in range(0, SAMPLES, 6):
            row = ", ".join(f"0x{v:05x}" for v in samples[i:i + 6])
            print(f"\t{row},")
        print("};")
    print()
    print("#endif /* AR_ISP_DRC_TAIL_H */")


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--lib", required=True, help="vendor libmpp_service.so")
    args = ap.parse_args()

    with open(args.lib, "rb") as handle:
        lib = handle.read()

    offset = TEMPLATE_VMA - VMA_TO_FILE
    if offset + TEMPLATE_LEN > len(lib):
        sys.exit(f"{args.lib}: template at 0x{offset:x} lies past the end of the file")
    template = lib[offset:offset + TEMPLATE_LEN]

    banks = [decode_bank(template, 0x1000), decode_bank(template, 0x1800)]
    emit(banks)
    return 0


if __name__ == "__main__":
    sys.exit(main())
