#!/usr/bin/env python3
"""
Extract the ISP gamma table's second page from the vendor library as a kernel header.

The gamma allocation's first 0x1000 bytes are the only part the hardware fetches, and they
are two 0x800 pages. Page 0 is AE-selected out of the tuning file and is generated at
runtime by ar-isp-codec.h. Page 1 is not in the tuning file in any form: it is a prepacked
constant in the vendor service library, which the dynamic gamma handler copies into its
working allocation before the packer overwrites page 0 and leaves page 1 alone.

The constant is byte-identical to page 1 of every capture we hold. Three sibling 0x1000
blocks at VMA 0x47e1a0, 0x47f1a0 and 0x4801a0 are identical to each other, and each is the
same 0x800 page stored twice, matching the three gamma descriptors that alias one buffer.

Emitted decoded, as a sample array rather than packed bytes, because the packing already
lives in ar-isp-codec.h and a curve is reviewable where a blob is not.

The library is proprietary and is not in the repository. Supply it with --lib. The generated
header is checked in, so this script is only rerun if the vendor library changes.

    kernel/scripts/gen-gamma-page1.py --lib out/air-gather/vendor-root/usr/lib/libmpp_service.so \\
        > overlay/drivers/media/artosyn/ar-isp-gamma-page1.h
"""

import argparse
import hashlib
import struct
import sys

# Second LOAD segment maps file 0x4004d0 at 0x4104d0, so VMA - 0x10000 is the file offset.
VMA_TO_FILE = 0x10000

PAGE1_VMA = 0x47E1A0
PAGE = 0x800
RECORDS = 128
SAMPLES = 512


def decode_page(data, base):
    """Undo the packing in ar-isp-codec.h: 128 records of four twelve-bit samples."""
    out = []
    for record in range(RECORDS):
        word0, word1, word2, _word3 = struct.unpack_from("<4I", data, base + record * 16)
        out.append(word0 & 0xFFF)
        out.append((word0 >> 12) & 0xFFF)
        out.append((word1 >> 16) & 0xFFF)
        out.append((word2 >> 8) & 0xFFF)

    return out


def forward_field(data, base):
    """The last record's mirror of the sample after the page. Not derivable from the samples."""
    word2 = struct.unpack_from("<I", data, base + (RECORDS - 1) * 16 + 8)[0]
    return (word2 >> 20) & 0xFFF


def emit(samples, tail, digest):
    print("/* SPDX-License-Identifier: GPL-2.0 */")
    print("/* Generated by kernel/scripts/gen-gamma-page1.py. Do not edit. */")
    print("/*")
    print(" * The gamma table's second page.")
    print(" *")
    print(" * Page 0 is AE-selected from the tuning file and generated at runtime. This one is")
    print(" * not in the tuning file at all, in packed or unpacked form, so it is carried: it is")
    print(" * a prepacked constant in the vendor service library, byte-identical to page 1 of")
    print(" * every capture we hold.")
    print(" *")
    print(" * The tail is the last record's forward field, which mirrors the sample after the")
    print(" * page and cannot be derived from the samples. Leaving it zero maps the brightest")
    print(" * inputs to black; see ar_isp_gamma_pack_page.")
    print(" *")
    print(f" * Source library sha256 {digest}.")
    print(" */")
    print()
    print("#ifndef AR_ISP_GAMMA_PAGE1_H")
    print("#define AR_ISP_GAMMA_PAGE1_H")
    print()
    print(f"#define AR_ISP_GAMMA_PAGE1_TAIL\t\t{tail}")
    print()
    print("static const u16 ar_isp_gamma_page1[AR_ISP_GAMMA_SAMPLES] = {")
    for i in range(0, SAMPLES, 8):
        row = ", ".join(f"{v:4d}" for v in samples[i:i + 8])
        print(f"\t{row},")
    print("};")
    print()
    print("#endif /* AR_ISP_GAMMA_PAGE1_H */")


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--lib", required=True, help="vendor libmpp_service.so")
    args = ap.parse_args()

    with open(args.lib, "rb") as handle:
        lib = handle.read()

    offset = PAGE1_VMA - VMA_TO_FILE
    if offset + 2 * PAGE > len(lib):
        sys.exit(f"{args.lib}: page 1 at 0x{offset:x} lies past the end of the file")
    block = lib[offset:offset + 2 * PAGE]

    if block[:PAGE] != block[PAGE:]:
        sys.exit(f"{args.lib}: the two halves at 0x{PAGE1_VMA:x} differ; the layout has changed")

    samples = decode_page(block, 0)
    for i in range(1, SAMPLES):
        if samples[i] < samples[i - 1]:
            sys.exit(f"{args.lib}: sample {i} decreases; this is not a transfer curve")

    emit(samples, forward_field(block, 0), hashlib.sha256(lib).hexdigest())
    return 0


if __name__ == "__main__":
    sys.exit(main())
