/* SPDX-License-Identifier: GPL-2.0 */
/* Generated by scripts/isp/gen-cvisp-setup.py. Do not edit. */
/*
 * CVISP register configuration, with a source for every value.
 *
 * Values come from the vendor's own CVISP static images (libmpp_service.so
 * sha256 4cfc8e6cfb42d8c821137993b95b152f, template array
 * entries 9, 0 and 55), from the configured frame geometry, or from a named
 * constant. The write ORDER is the streaming vendor's, taken from the MMIO
 * trace in ar-cvisp-defaults.h: no vendor code has been read that fixes the
 * order, and the staged enable at the end of setup shows the order matters.
 *
 * Row tags:
 *   library       the value the vendor's static image carries for that register
 *   geom          spelled out of the frame dimensions the driver configures
 *   zero          cleared; there is no vendor datum to source
 *   unity         a digital-gain bank the vendor holds at 1.0
 *   blc fallback  overwritten by ar_cvisp_blc_apply from the tuning blob on every
 *                 boot the firmware loads; a recording only in the degraded path
 *   scoreboard    accumulated per port by dvp_scaler_outlib_output_config
 *   vendor dram   a vendor buffer address ar_cvisp_arm_buffer overwrites when the
 *                 capture node streams
 *   residue       still a recording. Why it differs from the image is known, what
 *                 to write instead is not. check-cvisp-derivation.py lists them.
 *
 * This table is byte-identical to the recovered one by construction; the
 * generator fails rather than emitting a value it cannot reproduce.
 */

#ifndef AR_CVISP_DERIVED_H
#define AR_CVISP_DERIVED_H

struct ar_cvisp_reg {
	u16 off;
	u32 val;
};

struct ar_cvisp_bufset {
	u32 y;
	u32 u;
	u32 v;
};

/*
 * Output-descriptor setup, in the trace's write order with consecutive
 * duplicates collapsed, ending at the staged enable. Values from library
 * template entry 55 except where tagged otherwise.
 */
static const struct ar_cvisp_reg ar_cvisp_setup[] = {
	{ 0x8000, 0x00800800 },	/* library */
	{ 0x8004, 0x00000000 },	/* library */
	{ 0x8008, 0x021c03c0 },	/* library */
	{ 0x800c, 0x00000000 },	/* library */
	{ 0x8010, 0x021c03c0 },	/* library */
	{ 0x8014, 0x00000000 },	/* library */
	{ 0x8018, 0x04a40840 },	/* library */
	{ 0x801c, 0x00000000 },	/* library */
	{ 0x8020, 0x04a40840 },	/* library */
	{ 0x8024, 0x00000000 },	/* library */
	{ 0x8028, 0x04380780 },	/* library */
	{ 0x802c, 0x08000b33 },	/* library */
	{ 0x8030, 0x07800780 },	/* library */
	{ 0x8034, 0x04380438 },	/* library */
	{ 0x8038, 0x08000800 },	/* library */
	{ 0x803c, 0x3ffffc00 },	/* library */
	{ 0x8040, 0x3ffffc00 },	/* library */
	{ 0x8044, 0x021c03c0 },	/* library */
	{ 0x8048, 0x10800000 },	/* library */
	{ 0x804c, 0x00000000 },	/* library */
	{ 0x8050, 0x021c03c0 },	/* library */
	{ 0x8054, 0x08000b33 },	/* library */
	{ 0x8058, 0x03c003c0 },	/* library */
	{ 0x805c, 0x021c021c },	/* library */
	{ 0x8060, 0x08000800 },	/* library */
	{ 0x8064, 0x3ffffc00 },	/* library */
	{ 0x8068, 0x3ffffc00 },	/* library */
	{ 0x806c, 0x010e01e0 },	/* library */
	{ 0x8070, 0x10800000 },	/* library */
	{ 0x8074, 0x00000000 },	/* library */
	{ 0x8078, 0x04380780 },	/* library */
	{ 0x807c, 0x08000b33 },	/* library */
	{ 0x8080, 0x07800780 },	/* library */
	{ 0x8084, 0x04380438 },	/* library */
	{ 0x8088, 0x08000800 },	/* library */
	{ 0x808c, 0x3ffffc00 },	/* library */
	{ 0x8090, 0x3ffffc00 },	/* library */
	{ 0x8094, 0x04380780 },	/* library */
	{ 0x8098, 0x0a800000 },	/* vendor dram */
	{ 0x809c, 0x00000000 },	/* vendor dram */
	{ 0x80a0, 0x021c03c0 },	/* library */
	{ 0x80a4, 0x08000b33 },	/* library */
	{ 0x80a8, 0x03c003c0 },	/* library */
	{ 0x80ac, 0x021c021c },	/* library */
	{ 0x80b0, 0x08000800 },	/* library */
	{ 0x80b4, 0x3ffffc00 },	/* library */
	{ 0x80b8, 0x3ffffc00 },	/* library */
	{ 0x80bc, 0x021c03c0 },	/* library */
	{ 0x80c0, 0x0a800000 },	/* library */
	{ 0x80c4, 0x00000000 },	/* library */
	{ 0x80c8, 0x04380780 },	/* library */
	{ 0x80cc, 0x08000b33 },	/* library */
	{ 0x80d0, 0x07800780 },	/* library */
	{ 0x80d4, 0x04380438 },	/* library */
	{ 0x80d8, 0x08000800 },	/* library */
	{ 0x80dc, 0x3ffffc00 },	/* library */
	{ 0x80e0, 0x3ffffc00 },	/* library */
	{ 0x80e4, 0x021c03c0 },	/* library */
	{ 0x80e8, 0x10000000 },	/* library */
	{ 0x80ec, 0x00000000 },	/* library */
	{ 0x80f0, 0x021c03c0 },	/* library */
	{ 0x80f4, 0x08000b33 },	/* library */
	{ 0x80f8, 0x03c003c0 },	/* library */
	{ 0x80fc, 0x021c021c },	/* library */
	{ 0x8100, 0x08000800 },	/* library */
	{ 0x8104, 0x3ffffc00 },	/* library */
	{ 0x8108, 0x3ffffc00 },	/* library */
	{ 0x810c, 0x010e01e0 },	/* library */
	{ 0x8110, 0x10000000 },	/* library */
	{ 0x8114, 0x00000000 },	/* library */
	{ 0x8118, 0x08400000 },	/* library */
	{ 0x811c, 0x04a40000 },	/* library */
	{ 0x8120, 0x08400000 },	/* library */
	{ 0x8124, 0x04a40000 },	/* library */
	{ 0x8128, 0x08000800 },	/* library */
	{ 0x812c, 0x3ffffc00 },	/* library */
	{ 0x8130, 0x3ffffc00 },	/* library */
	{ 0x8134, 0x021c03c0 },	/* library */
	{ 0x8138, 0x06d00000 },	/* library */
	{ 0x813c, 0x00000000 },	/* library */
	{ 0x8140, 0x04380780 },	/* library */
	{ 0x8144, 0x08000b32 },	/* library */
	{ 0x8148, 0x07800780 },	/* library */
	{ 0x814c, 0x04380438 },	/* library */
	{ 0x8150, 0x08000800 },	/* library */
	{ 0x8154, 0x3ffffc00 },	/* library */
	{ 0x8158, 0x3ffffc00 },	/* library */
	{ 0x815c, 0x021c03c0 },	/* library */
	{ 0x8160, 0x07d00000 },	/* library */
	{ 0x8164, 0x00000000 },	/* library */
	{ 0x8168, 0x08d00000 },	/* library */
	{ 0x816c, 0x11800000 },	/* library */
	{ 0x8170, 0x0ad00000 },	/* library */
	{ 0x8174, 0x0b800000 },	/* vendor dram */
	{ 0x8178, 0x0cd00000 },	/* library */
	{ 0x817c, 0x11000000 },	/* library */
	{ 0x8180, 0x0ed00000 },	/* library */
	{ 0x8184, 0x0fd00000 },	/* library */
	{ 0x8188, 0x10d00000 },	/* library */
	{ 0x818c, 0x14800000 },	/* library */
	{ 0x8190, 0x12d00000 },	/* library */
	{ 0x8194, 0x0c800000 },	/* vendor dram */
	{ 0x8198, 0x14d00000 },	/* library */
	{ 0x819c, 0x14000000 },	/* library */
	{ 0x81a0, 0x16d00000 },	/* library */
	{ 0x81a4, 0x17d00000 },	/* library */
	{ 0x81a8, 0x00000000 },	/* library */
	{ 0x81ac, 0x00000000 },	/* library */
	{ 0x81b0, 0x00000000 },	/* library */
	{ 0x81b4, 0x00000000 },	/* library */
	{ 0x81b8, 0x00000000 },	/* library */
	{ 0x81bc, 0x00000000 },	/* library */
	{ 0x81c0, 0x00000000 },	/* library */
	{ 0x81c4, 0x00000000 },	/* library */
	{ 0x81c8, 0x0300003a },	/* library */
	{ 0x81cc, 0xa92c2020 },	/* library */
	{ 0x81d0, 0x00820000 },	/* library */
	{ 0x81d4, 0x009e001c },	/* library */
	{ 0x81d8, 0x00000000 },	/* library */
	{ 0x81dc, 0x00000000 },	/* library */
	{ 0x81e0, 0x00000000 },	/* library */
	{ 0x81e4, 0x00000000 },	/* library */
	{ 0x81e8, 0x00000000 },	/* library */
	{ 0x81ec, 0x00000000 },	/* library */
	{ 0x81f0, 0x00000000 },	/* library */
	{ 0x81f4, 0x00000000 },	/* library */
	{ 0x81f8, 0x00000000 },	/* library */
	{ 0x81fc, 0x00000000 },	/* library */
	{ 0x8200, 0x00000000 },	/* library */
	{ 0x8204, 0x00000000 },	/* library */
	{ 0x8208, 0x00000000 },	/* library */
	{ 0x820c, 0x00000000 },	/* library */
	{ 0x8210, 0x12800000 },	/* library */
	{ 0x8214, 0x13800000 },	/* library */
	{ 0x8218, 0x16800000 },	/* library */
	{ 0x821c, 0x00202040 },	/* library */
	{ 0x8220, 0x00000001 },	/* library */
	{ 0x8224, 0x00800000 },	/* library */
	{ 0x8228, 0x08800000 },	/* library */
	{ 0x822c, 0x10800000 },	/* library */
	{ 0x8230, 0x00000000 },	/* library */
	{ 0x8234, 0x00000000 },	/* library */
	{ 0x8238, 0x00000000 },	/* library */
	{ 0x823c, 0x01800000 },	/* library */
	{ 0x8240, 0x09800000 },	/* library */
	{ 0x8244, 0x11800000 },	/* library */
	{ 0x8248, 0x00000000 },	/* library */
	{ 0x824c, 0x00000000 },	/* library */
	{ 0x8250, 0x00000000 },	/* library */
	{ 0x8254, 0x02800000 },	/* library */
	{ 0x8258, 0x0a800000 },	/* library */
	{ 0x825c, 0x12800000 },	/* library */
	{ 0x8260, 0x00000000 },	/* library */
	{ 0x8264, 0x00000000 },	/* library */
	{ 0x8268, 0x00000000 },	/* library */
	{ 0x826c, 0x03800000 },	/* library */
	{ 0x8270, 0x0b800000 },	/* library */
	{ 0x8274, 0x13800000 },	/* library */
	{ 0x8278, 0x00000000 },	/* library */
	{ 0x827c, 0x00000000 },	/* library */
	{ 0x8280, 0x00000000 },	/* library */
	{ 0x8284, 0x04800000 },	/* library */
	{ 0x8288, 0x0c800000 },	/* library */
	{ 0x828c, 0x14800000 },	/* library */
	{ 0x8290, 0x00000000 },	/* library */
	{ 0x8294, 0x00000000 },	/* library */
	{ 0x8298, 0x00000000 },	/* library */
	{ 0x829c, 0x05800000 },	/* library */
	{ 0x82a0, 0x0d800000 },	/* library */
	{ 0x82a4, 0x15800000 },	/* library */
	{ 0x82a8, 0x00000000 },	/* library */
	{ 0x82ac, 0x00000000 },	/* library */
	{ 0x82b0, 0x00000000 },	/* library */
	{ 0x82b4, 0x06800000 },	/* library */
	{ 0x82b8, 0x0e800000 },	/* library */
	{ 0x82bc, 0x16800000 },	/* library */
	{ 0x82c0, 0x00000000 },	/* library */
	{ 0x82c4, 0x00000000 },	/* library */
	{ 0x82c8, 0x00000000 },	/* library */
	{ 0x82cc, 0x07800000 },	/* library */
	{ 0x82d0, 0x0f800000 },	/* library */
	{ 0x82d4, 0x17800000 },	/* library */
	{ 0x82d8, 0x00000000 },	/* library */
	{ 0x82dc, 0x00000000 },	/* library */
	{ 0x82e0, 0x00202000 },	/* library */
	{ 0x82e4, 0x00c00000 },	/* library */
	{ 0x82e8, 0x08c00000 },	/* library */
	{ 0x82ec, 0x10c00000 },	/* library */
	{ 0x82f0, 0x00202020 },	/* library */
	{ 0x82f4, 0x00202000 },	/* library */
	{ 0x82f8, 0x01c00000 },	/* library */
	{ 0x82fc, 0x09c00000 },	/* library */
	{ 0x8300, 0x11c00000 },	/* library */
	{ 0x8304, 0x00202020 },	/* library */
	{ 0x8308, 0x00404000 },	/* library */
	{ 0x830c, 0x02c00000 },	/* library */
	{ 0x8310, 0x0ac00000 },	/* library */
	{ 0x8314, 0x12c00000 },	/* library */
	{ 0x8318, 0x00202020 },	/* library */
	{ 0x831c, 0x00404000 },	/* library */
	{ 0x8320, 0x03c00000 },	/* library */
	{ 0x8324, 0x0bc00000 },	/* library */
	{ 0x8328, 0x13c00000 },	/* library */
	{ 0x832c, 0x00202020 },	/* library */
	{ 0x8330, 0x00606000 },	/* library */
	{ 0x8334, 0x04c00000 },	/* library */
	{ 0x8338, 0x0cc00000 },	/* library */
	{ 0x833c, 0x14c00000 },	/* library */
	{ 0x8340, 0x00202020 },	/* library */
	{ 0x8344, 0x00606000 },	/* library */
	{ 0x8348, 0x05c00000 },	/* library */
	{ 0x834c, 0x0dc00000 },	/* library */
	{ 0x8350, 0x15c00000 },	/* library */
	{ 0x8354, 0x00202020 },	/* library */
	{ 0x8358, 0x00606030 },	/* library */
	{ 0x835c, 0x06c00000 },	/* library */
	{ 0x8360, 0x0ec00000 },	/* library */
	{ 0x8364, 0x16c00000 },	/* library */
	{ 0x8368, 0x00202020 },	/* library */
	{ 0x836c, 0x00606030 },	/* library */
	{ 0x8370, 0x07c00000 },	/* library */
	{ 0x8374, 0x0fc00000 },	/* library */
	{ 0x8378, 0x17c00000 },	/* library */
	{ 0x837c, 0x00202020 },	/* library */
	{ 0x8024, 0x00ffffff },	/* scoreboard */
	{ 0x8000, 0x00800800 },	/* library */
	{ 0x8024, 0x00ffffff },	/* scoreboard */
	{ 0x8000, 0x00800800 },	/* library */
	{ 0x802c, 0x08000b32 },	/* residue */
	{ 0x8054, 0x08000b32 },	/* residue */
	{ 0x807c, 0x08000b32 },	/* residue */
	{ 0x80a4, 0x08000b32 },	/* residue */
	{ 0x80cc, 0x08000b32 },	/* residue */
	{ 0x80f4, 0x08000b32 },	/* residue */
	{ 0x811c, 0x04a40000 },	/* library */
	{ 0x8144, 0x00000000 },	/* residue */
	{ 0x8008, 0x021c0780 },	/* geom: height / 2 << 16 | width */
	{ 0x8008, 0x04380780 },	/* geom: height << 16 | width */
	{ 0x8010, 0x021c03c0 },	/* library */
	{ 0x8004, 0x00000000 },	/* library */
	{ 0x800c, 0x00000000 },	/* library */
	{ 0x809c, 0x00000800 },	/* vendor dram */
	{ 0x81c8, 0x03000030 },	/* residue */
	{ 0x8078, 0x04380780 },	/* library */
	{ 0x8094, 0x04380780 },	/* library */
	{ 0x80a0, 0x021c03c0 },	/* library */
	{ 0x80bc, 0x021c03c0 },	/* library */
	{ 0x81b4, 0x00000400 },	/* residue */
	{ 0x81b4, 0x04000400 },	/* residue */
	{ 0x8024, 0x00ffffff },	/* scoreboard */
	{ 0x8098, 0x28014000 },	/* vendor dram */
	{ 0x8174, 0x28232000 },	/* vendor dram */
	{ 0x8194, 0x282bb000 },	/* vendor dram */
	{ 0x8000, 0x00800802 },	/* residue */
	{ 0x8000, 0x00800806 },	/* residue */
};

/*
 * The tail that follows the enable: arbitration (entry 9), frame geometry
 * and limits (entry 0), the BLC fallback ar_cvisp_blc_apply overwrites from
 * the tuning blob, and the digital-gain banks the vendor holds at unity.
 */
static const struct ar_cvisp_reg ar_cvisp_late[] = {
	{ 0x807c, 0x08000b33 },	/* library */
	{ 0x80a4, 0x08000b33 },	/* library */
	{ 0x4000, 0x00000780 },	/* library */
	{ 0x4004, 0x00000438 },	/* library */
	{ 0x4008, 0x00000780 },	/* library */
	{ 0x400c, 0x00000438 },	/* library */
	{ 0x4010, 0x00002980 },	/* library */
	{ 0x4014, 0x00000000 },	/* library */
	{ 0x4018, 0x00000032 },	/* library */
	{ 0x401c, 0x00000032 },	/* library */
	{ 0x4020, 0x00000418 },	/* library */
	{ 0x4024, 0x000003e8 },	/* library */
	{ 0x4028, 0x00000032 },	/* library */
	{ 0x402c, 0x00000032 },	/* library */
	{ 0x4030, 0x00004e20 },	/* library */
	{ 0x4200, 0x0000f040 },	/* blc fallback */
	{ 0x4204, 0x0000f040 },	/* blc fallback */
	{ 0x4208, 0x0000f040 },	/* blc fallback */
	{ 0x420c, 0x0000f040 },	/* blc fallback */
	{ 0x4210, 0x0000f040 },	/* blc fallback */
	{ 0x4214, 0x0000f040 },	/* blc fallback */
	{ 0x4218, 0x0000f040 },	/* blc fallback */
	{ 0x421c, 0x0000f040 },	/* blc fallback */
	{ 0x4220, 0x00000110 },	/* blc fallback */
	{ 0x4224, 0x00000110 },	/* blc fallback */
	{ 0x4228, 0x00000110 },	/* blc fallback */
	{ 0x422c, 0x00000110 },	/* blc fallback */
	{ 0x4230, 0x00000110 },	/* blc fallback */
	{ 0x4234, 0x00000110 },	/* blc fallback */
	{ 0x4238, 0x00000110 },	/* blc fallback */
	{ 0x423c, 0x00000110 },	/* blc fallback */
	{ 0x4610, 0x00000100 },	/* unity */
	{ 0x4614, 0x00000100 },	/* unity */
	{ 0x4618, 0x00000100 },	/* unity */
	{ 0x461c, 0x00000100 },	/* unity */
	{ 0x4620, 0x00000000 },	/* unity */
	{ 0x4624, 0x00000000 },	/* unity */
	{ 0x4628, 0x00000000 },	/* unity */
	{ 0x462c, 0x00000000 },	/* unity */
	{ 0x4630, 0x00000000 },	/* unity */
	{ 0x4634, 0x00000000 },	/* unity */
	{ 0x4638, 0x00000000 },	/* unity */
	{ 0x463c, 0x00000000 },	/* unity */
	{ 0x4710, 0x00000100 },	/* unity */
	{ 0x4714, 0x00000100 },	/* unity */
	{ 0x4718, 0x00000100 },	/* unity */
	{ 0x471c, 0x00000100 },	/* unity */
	{ 0x4720, 0x00000000 },	/* unity */
	{ 0x4724, 0x00000000 },	/* unity */
	{ 0x4728, 0x00000000 },	/* unity */
	{ 0x472c, 0x00000000 },	/* unity */
	{ 0x4730, 0x00000000 },	/* unity */
	{ 0x4734, 0x00000000 },	/* unity */
	{ 0x4738, 0x00000000 },	/* unity */
	{ 0x473c, 0x00000000 },	/* unity */
	{ 0x0000, 0x00006003 },	/* library */
	{ 0x0004, 0x00006004 },	/* library */
	{ 0x0008, 0x00006005 },	/* library */
	{ 0x000c, 0x00006006 },	/* library */
	{ 0x0010, 0x00006007 },	/* library */
	{ 0x0014, 0x00006008 },	/* library */
	{ 0x0018, 0x00006009 },	/* library */
	{ 0x001c, 0x0000600a },	/* library */
	{ 0x0020, 0x00008003 },	/* library */
	{ 0x0024, 0x00008008 },	/* library */
	{ 0x0028, 0x0000800e },	/* library */
	{ 0x002c, 0x0000800f },	/* library */
	{ 0x0030, 0x00008013 },	/* library */
	{ 0x0034, 0x0000801a },	/* library */
	{ 0x0038, 0x0000801b },	/* library */
	{ 0x003c, 0x0000801c },	/* library */
	{ 0x0040, 0x0000a005 },	/* library */
	{ 0x0044, 0x0000a00a },	/* library */
	{ 0x0048, 0x0000a010 },	/* library */
	{ 0x004c, 0x0000a011 },	/* library */
	{ 0x0050, 0x0000a015 },	/* library */
	{ 0x0054, 0x0000a01c },	/* library */
	{ 0x0058, 0x0000a01d },	/* library */
	{ 0x005c, 0x0000a01e },	/* library */
	{ 0x0060, 0x0000c006 },	/* library */
	{ 0x0064, 0x0000c00b },	/* library */
	{ 0x0068, 0x0000c011 },	/* library */
	{ 0x006c, 0x0000c012 },	/* library */
	{ 0x0070, 0x0000c016 },	/* library */
	{ 0x0074, 0x0000c01d },	/* library */
	{ 0x0078, 0x0000c01e },	/* library */
	{ 0x007c, 0x0000c01f },	/* library */
	{ 0x0080, 0x03ffffff },	/* library */
	{ 0x0084, 0x03ffffff },	/* library */
	{ 0x0088, 0x03ffffff },	/* library */
	{ 0x008c, 0x03ffffff },	/* library */
	{ 0x0090, 0x03ffffff },	/* library */
	{ 0x0094, 0x03ffffff },	/* library */
	{ 0x0098, 0x03ffffff },	/* library */
	{ 0x009c, 0x03ffffff },	/* library */
	{ 0x00a0, 0x00000000 },	/* zero */
	{ 0x00a4, 0x00000000 },	/* zero */
	{ 0x00a8, 0x00000000 },	/* zero */
	{ 0x00ac, 0x00000000 },	/* zero */
	{ 0x4104, 0x00000780 },	/* geom: width */
	{ 0x410c, 0x00000438 },	/* geom: height */
};

/* The per-frame rewrite of the digital-gain head, all unity. */
static const struct ar_cvisp_reg ar_cvisp_tick[] = {
	{ 0x4600, 0x00000100 },	/* unity */
	{ 0x4604, 0x00000100 },	/* unity */
	{ 0x4608, 0x00000100 },	/* unity */
	{ 0x460c, 0x00000100 },	/* unity */
	{ 0x4700, 0x00000100 },	/* unity */
	{ 0x4704, 0x00000100 },	/* unity */
	{ 0x4708, 0x00000100 },	/* unity */
	{ 0x470c, 0x00000100 },	/* unity */
};

/*
 * The vendor's own five-slot plane ring. These are DRAM addresses, not
 * configuration: ar_cvisp_arm_buffer replaces all three the moment the capture
 * node streams, and they survive only on the idle ring path, which is what
 * makes a /dev/mem read of a vendor-addressed frame possible. Carried.
 */
static const struct ar_cvisp_bufset ar_cvisp_ring[] = {
	{ 0x2834c000, 0x2856a000, 0x285f3000 },
	{ 0x28684000, 0x288a2000, 0x2892b000 },
	{ 0x289bc000, 0x28bda000, 0x28c63000 },
	{ 0x28cf4000, 0x28f12000, 0x28f9b000 },
	{ 0x28014000, 0x28232000, 0x282bb000 },
};

#endif /* AR_CVISP_DERIVED_H */
