/* SPDX-License-Identifier: GPL-2.0 */
/* Generated by kernel/scripts/isp/isp-gates.py --header. Do not edit. */
/*
 * Which register and bit gates each ISP submodule, and where the tuning file
 * decides it.
 *
 * Recovered from libmpp_service.so by kernel/scripts/isp/isp-gates.py; see
 * plans/isp-stage-gates.md for the mechanism. Nothing here is inferred from a
 * capture: the register and the masks come from the library's own read-modify
 * writes, and the polarity from which side of the tuning-flag branch the set
 * sits on. Each row carries how its polarity was settled, `code` where the
 * branch gives it directly and `paired` where it comes from the tuning flag
 * and a live register agreeing.
 *
 * set_mask is what the enable path sets; clear_mask is what the disable path
 * clears, which for the top-level stages is the gate bit together with a
 * companion the vendor always clears with it (ccm1 23, drc 20, gamma 30).
 * What those companions select is not recovered, so they are carried exactly
 * as the library writes them rather than narrowed to a guess.
 *
 * blob_gate is the offset of the stage's gate flag in the sensor tuning file,
 * or 0 for the stages that read no flag at all. Those carry AR_ISP_STAGE_NO_BLOB
 * and their state is whatever the configure path produced: no gate state is
 * invented here that the library was not seen to decide.
 */

#ifndef AR_ISP_GATES_H
#define AR_ISP_GATES_H

/*
 * How a stage is turned off. A bit gate is read-modify-written and its
 * polarity says which way means running; a word gate is written zero to stop
 * the stage and a computed value to start it, so its "on" cannot be
 * synthesised from this table.
 */
#define AR_ISP_GATE_UNKNOWN		0
#define AR_ISP_GATE_BIT_ENABLE		1
#define AR_ISP_GATE_BIT_BYPASS		2
#define AR_ISP_GATE_WORD		3

/* Owns a DMA table fetch. */
#define AR_ISP_STAGE_FETCH		0x01
/* Reads no tuning flag, so the file cannot say what it should be. */
#define AR_ISP_STAGE_NO_BLOB		0x02

struct ar_isp_gate {
	u16 reg;
	u32 set_mask;
	u32 clear_mask;
	u8 kind;
};

struct ar_isp_stage {
	const char *name;
	u16 bank;
	u32 blob_gate;
	const struct ar_isp_gate *gates;
	u8 n_gates;
	u8 flags;
};

static const struct ar_isp_gate ar_isp_gates_acm[] = {
	{ 0x7600, 0x00000001, 0x00000001, AR_ISP_GATE_BIT_BYPASS },	/* code */
};

static const struct ar_isp_gate ar_isp_gates_af_stats[] = {
	{ 0x7400, 0x00000001, 0x00000001, AR_ISP_GATE_BIT_BYPASS },	/* paired */
	{ 0x7558, 0x00000040, 0x0000007f, AR_ISP_GATE_BIT_ENABLE },	/* paired */
	{ 0x75ac, 0x00000000, 0x00000000, AR_ISP_GATE_WORD },	/* word */
	{ 0x75b0, 0x00000000, 0x00000000, AR_ISP_GATE_WORD },	/* word */
};

static const struct ar_isp_gate ar_isp_gates_awbs_stats[] = {
	{ 0x6c00, 0x00000001, 0x00000001, AR_ISP_GATE_BIT_ENABLE },	/* code */
};

static const struct ar_isp_gate ar_isp_gates_binning_filter[] = {
	{ 0x3c40, 0x00000001, 0x00000001, AR_ISP_GATE_BIT_ENABLE },	/* code */
};

static const struct ar_isp_gate ar_isp_gates_birnr[] = {
	{ 0x1800, 0x00000001, 0x00000001, AR_ISP_GATE_BIT_BYPASS },	/* code */
};

static const struct ar_isp_gate ar_isp_gates_blc[] = {
	{ 0x0000, 0x00000004, 0x00000404, AR_ISP_GATE_BIT_ENABLE },	/* code */
};

static const struct ar_isp_gate ar_isp_gates_ccm1[] = {
	{ 0x0000, 0x00200000, 0x00a00000, AR_ISP_GATE_BIT_ENABLE },	/* code */
};

static const struct ar_isp_gate ar_isp_gates_cfa[] = {
	{ 0x0800, 0x00010000, 0x00010000, AR_ISP_GATE_UNKNOWN },	/* unresolved */
};

static const struct ar_isp_gate ar_isp_gates_cm[] = {
	{ 0x4838, 0x00000000, 0x00000000, AR_ISP_GATE_WORD },	/* word */
};

static const struct ar_isp_gate ar_isp_gates_cm2[] = {
	{ 0x4800, 0x00000001, 0x00000001, AR_ISP_GATE_BIT_ENABLE },	/* code */
};

static const struct ar_isp_gate ar_isp_gates_cnf[] = {
	{ 0x3c64, 0x00000001, 0x00000001, AR_ISP_GATE_BIT_ENABLE },	/* code */
};

static const struct ar_isp_gate ar_isp_gates_compander[] = {
	{ 0x0000, 0x00000020, 0x00002020, AR_ISP_GATE_BIT_ENABLE },	/* paired */
	{ 0x0000, 0x00002000, 0x00002020, AR_ISP_GATE_BIT_ENABLE },	/* paired */
};

static const struct ar_isp_gate ar_isp_gates_de3d[] = {
	{ 0x2e00, 0x00000001, 0x00000001, AR_ISP_GATE_UNKNOWN },	/* unresolved */
};

static const struct ar_isp_gate ar_isp_gates_decompander[] = {
	{ 0x0000, 0x00020000, 0x00020000, AR_ISP_GATE_BIT_ENABLE },	/* paired */
};

static const struct ar_isp_gate ar_isp_gates_derolling_stats[] = {
	{ 0x3900, 0x00000001, 0x00000001, AR_ISP_GATE_BIT_ENABLE },	/* code */
	{ 0x3900, 0x00000040, 0x00000040, AR_ISP_GATE_BIT_ENABLE },	/* code */
};

static const struct ar_isp_gate ar_isp_gates_digigain1[] = {
	{ 0x0000, 0x00000010, 0x00000010, AR_ISP_GATE_BIT_BYPASS },	/* paired */
};

static const struct ar_isp_gate ar_isp_gates_dpc[] = {
	{ 0x0c10, 0x00000001, 0x00000001, AR_ISP_GATE_BIT_ENABLE },	/* paired */
	{ 0x0c10, 0x00000002, 0x00000002, AR_ISP_GATE_BIT_BYPASS },	/* code */
	{ 0x0c10, 0x00000004, 0x00000004, AR_ISP_GATE_BIT_BYPASS },	/* paired */
};

static const struct ar_isp_gate ar_isp_gates_drc[] = {
	{ 0x0000, 0x00080000, 0x00180000, AR_ISP_GATE_BIT_ENABLE },	/* code */
	{ 0x0018, 0x00010000, 0x00010000, AR_ISP_GATE_BIT_ENABLE },	/* paired */
};

static const struct ar_isp_gate ar_isp_gates_drc_stats[] = {
	{ 0x300c, 0x00040000, 0x00040000, AR_ISP_GATE_UNKNOWN },	/* unresolved */
};

static const struct ar_isp_gate ar_isp_gates_face_rro_stats[] = {
	{ 0x64c8, 0x00000000, 0x00000000, AR_ISP_GATE_WORD },	/* word */
};

static const struct ar_isp_gate ar_isp_gates_fpn[] = {
	{ 0x4400, 0x00000010, 0x00000010, AR_ISP_GATE_UNKNOWN },	/* unresolved */
};

static const struct ar_isp_gate ar_isp_gates_gamma[] = {
	{ 0x0000, 0x20000000, 0x60000000, AR_ISP_GATE_BIT_ENABLE },	/* code */
	{ 0x0018, 0x00020000, 0x00020000, AR_ISP_GATE_BIT_BYPASS },	/* paired */
};

static const struct ar_isp_gate ar_isp_gates_gib[] = {
	{ 0x2408, 0x40000000, 0x40000000, AR_ISP_GATE_BIT_BYPASS },	/* code */
};

static const struct ar_isp_gate ar_isp_gates_gtm2[] = {
	{ 0x2800, 0x00000010, 0x00000010, AR_ISP_GATE_BIT_ENABLE },	/* code */
	{ 0x2800, 0x00000800, 0x00000800, AR_ISP_GATE_BIT_ENABLE },	/* code */
};

static const struct ar_isp_gate ar_isp_gates_hdr_awbs_stats[] = {
	{ 0x1e4c, 0x00000000, 0x00000000, AR_ISP_GATE_WORD },	/* word */
};

static const struct ar_isp_gate ar_isp_gates_hdr_lsc[] = {
	{ 0x1df0, 0x00000000, 0x00000000, AR_ISP_GATE_WORD },	/* word */
	{ 0x1e34, 0x00000000, 0x00000000, AR_ISP_GATE_WORD },	/* word */
};

static const struct ar_isp_gate ar_isp_gates_ir_lms_horz[] = {
	{ 0x8604, 0x00000000, 0x00000000, AR_ISP_GATE_WORD },	/* word */
};

static const struct ar_isp_gate ar_isp_gates_ir_nbbc[] = {
	{ 0x9000, 0x00000001, 0x00000001, AR_ISP_GATE_UNKNOWN },	/* unresolved */
};

static const struct ar_isp_gate ar_isp_gates_ir_rnr[] = {
	{ 0x8400, 0x00000001, 0x00000001, AR_ISP_GATE_BIT_BYPASS },	/* code */
};

static const struct ar_isp_gate ar_isp_gates_ir_stats[] = {
	{ 0x8a10, 0x00000001, 0x00000001, AR_ISP_GATE_UNKNOWN },	/* unresolved */
	{ 0x8a24, 0x00000001, 0x00000001, AR_ISP_GATE_UNKNOWN },	/* unresolved */
	{ 0x8a24, 0x00000010, 0x00000010, AR_ISP_GATE_UNKNOWN },	/* unresolved */
};

static const struct ar_isp_gate ar_isp_gates_lee_lnr[] = {
	{ 0x3cc8, 0x00000001, 0x00000001, AR_ISP_GATE_BIT_ENABLE },	/* code */
};

static const struct ar_isp_gate ar_isp_gates_lms[] = {
	{ 0x7268, 0x00000000, 0x00000000, AR_ISP_GATE_WORD },	/* word */
};

static const struct ar_isp_gate ar_isp_gates_lsc[] = {
	{ 0x4c00, 0x00000001, 0x00000001, AR_ISP_GATE_BIT_ENABLE },	/* code */
	{ 0x4c24, 0x00000004, 0x000000ff, AR_ISP_GATE_BIT_ENABLE },	/* paired */
	{ 0x4c24, 0x00000010, 0x000000ff, AR_ISP_GATE_BIT_ENABLE },	/* paired */
	{ 0x4c24, 0x00000020, 0x000000ff, AR_ISP_GATE_BIT_ENABLE },	/* paired */
};

static const struct ar_isp_gate ar_isp_gates_ltm[] = {
	{ 0x2800, 0x00000010, 0x00000010, AR_ISP_GATE_UNKNOWN },	/* unresolved */
	{ 0x2800, 0x00000800, 0x00000800, AR_ISP_GATE_UNKNOWN },	/* unresolved */
};

static const struct ar_isp_gate ar_isp_gates_lut3d[] = {
	{ 0x5800, 0x00000001, 0x00000003, AR_ISP_GATE_BIT_ENABLE },	/* code */
	{ 0x580c, 0x00000000, 0x00000000, AR_ISP_GATE_WORD },	/* word */
	{ 0x5824, 0x00000000, 0x00000000, AR_ISP_GATE_WORD },	/* word */
	{ 0x583c, 0x00000000, 0x00000000, AR_ISP_GATE_WORD },	/* word */
	{ 0x5854, 0x00000000, 0x00000000, AR_ISP_GATE_WORD },	/* word */
	{ 0x5864, 0x00000000, 0x00000000, AR_ISP_GATE_WORD },	/* word */
};

static const struct ar_isp_gate ar_isp_gates_nuc_dpc[] = {
	{ 0x7238, 0x00000080, 0x00000080, AR_ISP_GATE_UNKNOWN },	/* unresolved */
};

static const struct ar_isp_gate ar_isp_gates_qgg[] = {
	{ 0x7230, 0x00000001, 0x0000000f, AR_ISP_GATE_UNKNOWN },	/* unresolved */
};

static const struct ar_isp_gate ar_isp_gates_raw_3dnr[] = {
	{ 0x4000, 0x00000001, 0x00000001, AR_ISP_GATE_BIT_ENABLE },	/* code */
	{ 0x4000, 0x00000002, 0x00000006, AR_ISP_GATE_UNKNOWN },	/* unresolved */
	{ 0x4000, 0x00000004, 0x00000006, AR_ISP_GATE_UNKNOWN },	/* unresolved */
	{ 0x4000, 0x00000040, 0x00003fc0, AR_ISP_GATE_UNKNOWN },	/* unresolved */
	{ 0x4000, 0x00000080, 0x00003fc0, AR_ISP_GATE_UNKNOWN },	/* unresolved */
	{ 0x4000, 0x00000100, 0x00003fc0, AR_ISP_GATE_BIT_ENABLE },	/* code */
	{ 0x4000, 0x00000200, 0x00003fc0, AR_ISP_GATE_BIT_ENABLE },	/* code */
};

static const struct ar_isp_gate ar_isp_gates_raw_his_stats[] = {
	{ 0x6000, 0x00000001, 0x00000001, AR_ISP_GATE_BIT_ENABLE },	/* code */
};

static const struct ar_isp_gate ar_isp_gates_rgb2yuv[] = {
	{ 0x0000, 0x80000000, 0x90000000, AR_ISP_GATE_UNKNOWN },	/* unresolved */
};

static const struct ar_isp_gate ar_isp_gates_rgb_his_stats[] = {
	{ 0x5c00, 0x00000001, 0x00000001, AR_ISP_GATE_BIT_ENABLE },	/* code */
};

static const struct ar_isp_gate ar_isp_gates_rgb_max_stats[] = {
	{ 0x5400, 0x00000000, 0x00000000, AR_ISP_GATE_WORD },	/* word */
};

static const struct ar_isp_gate ar_isp_gates_rnr[] = {
	{ 0x1800, 0x00000001, 0x00000001, AR_ISP_GATE_BIT_BYPASS },	/* code */
};

static const struct ar_isp_gate ar_isp_gates_rro_stats[] = {
	{ 0x6400, 0x00000001, 0x00000001, AR_ISP_GATE_BIT_ENABLE },	/* code */
};

static const struct ar_isp_gate ar_isp_gates_wb[] = {
	{ 0x5000, 0x00000000, 0x00000000, AR_ISP_GATE_WORD },	/* word */
};

static const struct ar_isp_stage ar_isp_stages[] = {
	{ "acm", 0x7600, 0x0b00b8, ar_isp_gates_acm, 1, 0 },
	{ "af_stats", 0x7400, 0x0d5484, ar_isp_gates_af_stats, 4, 0 },
	{ "awbs_stats", 0x6c00, 0x0bbe98, ar_isp_gates_awbs_stats, 1, 0 },
	{ "binning_filter", 0x3c40, 0x0b6348, ar_isp_gates_binning_filter, 1, 0 },
	{ "birnr", 0x1800, 0x0b3550, ar_isp_gates_birnr, 1, 0 },
	{ "blc", 0x4200, 0x000024, ar_isp_gates_blc, 1, 0 },
	{ "ccm1", 0x3400, 0x0253fc, ar_isp_gates_ccm1, 1, 0 },
	{ "cfa", 0x0800, 0x000000, ar_isp_gates_cfa, 1, AR_ISP_STAGE_NO_BLOB },
	{ "cm", 0x4834, 0x089cfc, ar_isp_gates_cm, 1, 0 },
	{ "cm2", 0x4800, 0x0a1304, ar_isp_gates_cm2, 1, 0 },
	{ "cnf", 0x3c64, 0x08e198, ar_isp_gates_cnf, 1, 0 },
	{ "compander", 0x0000, 0x006cc4, ar_isp_gates_compander, 2, 0 },
	{ "de3d", 0x2e00, 0x000000, ar_isp_gates_de3d, 1, AR_ISP_STAGE_NO_BLOB },
	{ "decompander", 0x0000, 0x00906c, ar_isp_gates_decompander, 1, 0 },
	{ "derolling_stats", 0x3900, 0x0b64f8, ar_isp_gates_derolling_stats, 2, 0 },
	{ "digigain1", 0x4600, 0x0b4000, ar_isp_gates_digigain1, 1, 0 },
	{ "dpc", 0x0c00, 0x006ce8, ar_isp_gates_dpc, 3, 0 },
	{ "drc", 0x3000, 0x017a88, ar_isp_gates_drc, 2, AR_ISP_STAGE_FETCH },
	{ "drc_stats", 0x300c, 0x000000, ar_isp_gates_drc_stats, 1, AR_ISP_STAGE_NO_BLOB },
	{ "face_rro_stats", 0x64c8, 0x0b64f8, ar_isp_gates_face_rro_stats, 1, 0 },
	{ "fpn", 0x4400, 0x000000, ar_isp_gates_fpn, 1, AR_ISP_STAGE_NO_BLOB },
	{ "gamma", 0x0000, 0x026afc, ar_isp_gates_gamma, 2, AR_ISP_STAGE_FETCH },
	{ "gib", 0x2400, 0x0243e4, ar_isp_gates_gib, 1, 0 },
	{ "gtm2", 0x2800, 0x07abd8, ar_isp_gates_gtm2, 2, AR_ISP_STAGE_FETCH },
	{ "hdr_awbs_stats", 0x1e44, 0x0bbe98, ar_isp_gates_hdr_awbs_stats, 1, 0 },
	{ "hdr_lsc", 0x1dd0, 0x0a16c0, ar_isp_gates_hdr_lsc, 2, 0 },
	{ "ir_lms_horz", 0x8604, 0x0b4ee4, ar_isp_gates_ir_lms_horz, 1, 0 },
	{ "ir_nbbc", 0x9000, 0x000000, ar_isp_gates_ir_nbbc, 1, AR_ISP_STAGE_NO_BLOB },
	{ "ir_rnr", 0x8400, 0x0b2bf4, ar_isp_gates_ir_rnr, 1, 0 },
	{ "ir_stats", 0x8a10, 0x000000, ar_isp_gates_ir_stats, 3, AR_ISP_STAGE_NO_BLOB },
	{ "lee_lnr", 0x3cc8, 0x089e88, ar_isp_gates_lee_lnr, 1, 0 },
	{ "lms", 0x7264, 0x0b288c, ar_isp_gates_lms, 1, 0 },
	{ "lsc", 0x4c00, 0x009090, ar_isp_gates_lsc, 4, AR_ISP_STAGE_FETCH },
	{ "ltm", 0x2800, 0x000000, ar_isp_gates_ltm, 2, AR_ISP_STAGE_FETCH | AR_ISP_STAGE_NO_BLOB },
	{ "lut3d", 0x5800, 0x07b634, ar_isp_gates_lut3d, 6, 0 },
	{ "nuc_dpc", 0x7200, 0x000000, ar_isp_gates_nuc_dpc, 1, AR_ISP_STAGE_NO_BLOB },
	{ "qgg", 0x7230, 0x000000, ar_isp_gates_qgg, 1, AR_ISP_STAGE_NO_BLOB },
	{ "raw_3dnr", 0x4000, 0x0b500c, ar_isp_gates_raw_3dnr, 7, 0 },
	{ "raw_his_stats", 0x6000, 0x0b64f8, ar_isp_gates_raw_his_stats, 1, 0 },
	{ "rgb2yuv", 0x3c00, 0x000000, ar_isp_gates_rgb2yuv, 1, AR_ISP_STAGE_NO_BLOB },
	{ "rgb_his_stats", 0x5c00, 0x0b64f8, ar_isp_gates_rgb_his_stats, 1, 0 },
	{ "rgb_max_stats", 0x5400, 0x0b64f8, ar_isp_gates_rgb_max_stats, 1, 0 },
	{ "rnr", 0x1800, 0x0079d8, ar_isp_gates_rnr, 1, 0 },
	{ "rro_stats", 0x6400, 0x0b64f8, ar_isp_gates_rro_stats, 1, 0 },
	{ "wb", 0x5000, 0x000000, ar_isp_gates_wb, 1, AR_ISP_STAGE_NO_BLOB },
};

#endif /* AR_ISP_GATES_H */
