/* SPDX-License-Identifier: GPL-2.0 */
/* Generated by kernel/scripts/isp/gen-blob-header.py. Do not edit. */
/*
 * Where each tuning-blob field lives. Source: kernel/scripts/isp/blob-layout.toml.
 *
 * _BLOB_ names are absolute offsets in the file. _HDR_ names are displacements within
 * their header: AR_ISP_RNR_BLOB_HEADER + AR_ISP_RNR_HDR_MODE is 0x79e0.
 */
#ifndef AR_ISP_BLOB_H
#define AR_ISP_BLOB_H

#define AR_ISP_TUNING_SIZE		0xd6c58

/* blc_ladder: gain ladder, 5 float pairs */
#define AR_ISP_BLC_BLOB_LADDER      0x34

/* blc_entries: 5 pedestal records; four scale lanes then four level lanes */
#define AR_ISP_BLC_ENTRIES          0x5
#define AR_ISP_BLC_GROUP_OFF        0x10
#define AR_ISP_BLC_ENTRY_SIZE       0x20
#define AR_ISP_BLC_BLOB_TABLE       0xb4

/* rnr_header: rnr is the only one of the five with a mode word; the others start their count at 0x08 */
#define AR_ISP_LADDER_HDR_ENABLE    0x0
#define AR_ISP_LADDER_HDR_INTERP    0x4
#define AR_ISP_RNR_HDR_MODE         0x8
#define AR_ISP_RNR_HDR_COUNT        0xc
#define AR_ISP_RNR_HDR_SELECT       0x10
#define AR_ISP_RNR_BLOB_HEADER      0x79d8

/* rnr_bands: band abscissas, gain axis 1.0 to 2048 */
#define AR_ISP_RNR_BLOB_BANDS       0x79ec

/* rnr_payload: words 2..13 feed the low register halves, 14..25 the high halves */
#define AR_ISP_RNR_BANDS            0xc
#define AR_ISP_RNR_BLOB_STRIDE      0x160
#define AR_ISP_RNR_BLOB_PAYLOAD     0x7a6c

/* lsc_grid_y: record 0 grid 0, the third field of each point */
#define AR_ISP_LSC_GRID             0x64
#define AR_ISP_LSC_BLOB_Y           0x910c

/* lsc_grid_x: record 0 grid 1, the duplicated field */
#define AR_ISP_LSC_BLOB_X           0x929c

/* drc_header: the gate is this header's enable word; count at 0x17a90, band table at 0x17a9c */
#define AR_ISP_DRC_BLOB_HEADER      0x17a88
#define AR_ISP_DRC_BLOB_COUNT       0x17a90

/* drc_bands: 6 profiles x 2 edges: 0-80, 100-130, 150-180, 210-270, 290-380, 410-500 */
#define AR_ISP_DRC_BLOB_BANDS       0x17a9c

/* drc_profiles: first four populated; profiles 4 and 5 hold under a dozen non-zero bytes each. Each profile's first two 0x404 windows decode to a 257-sample curve through the 20-bit three-lane codec in glue/isp/drc-codec.py. */
#define AR_ISP_DRC_BLOB_PROFILES    0x6
#define AR_ISP_DRC_BLOB_STRIDE      0xc8c
#define AR_ISP_DRC_BLOB_OFFSET      0x17b1c

/* cfa_header */
#define AR_ISP_CFA_HDR_COUNT        0x8
#define AR_ISP_CFA_HDR_SELECT       0xc
#define AR_ISP_CFA_BLOB_HEADER      0x24548

/* cfa_bands */
#define AR_ISP_CFA_BLOB_BANDS       0x24558

/* cfa_payload */
#define AR_ISP_CFA_BANDS            0x5
#define AR_ISP_CFA_BLOB_STRIDE      0xa4
#define AR_ISP_CFA_BLOB_PAYLOAD     0x245d8

/* ccm1_gate: clear on this unit, so ccm1 keeps the identity matrix. That is vendor behaviour, not a failure. */
#define AR_ISP_CCM_BLOB_GATE        0x253fc

/* ccm_illuminants: illuminant ladder; matrices are Q8 sign-magnitude */
#define AR_ISP_CCM_BLOB_ILLUMINANTS 0x8
#define AR_ISP_CCM_BLOB_LADDER      0x25438

/* ccm_banks: 4 of the 8 allocated banks are used */
#define AR_ISP_CCM_BLOB_BANKS_USED  0x4
#define AR_ISP_CCM_BLOB_BANK_STRIDE 0x24
#define AR_ISP_CCM_BLOB_BANKS       0x25470

/* ccm2_gate */
#define AR_ISP_CCM2_BLOB_GATE       0x2595c

/* gamma_header: curve count 5 at 0x26b04, band table at 0x26b0c */
#define AR_ISP_GAMMA_BLOB_HEADER    0x26afc
#define AR_ISP_GAMMA_BLOB_COUNT     0x26b04

/* gamma_bands: 5 curves x 2 edges: 0-40, 80-130, 150-250, 280-330, 360-450 */
#define AR_ISP_GAMMA_BLOB_BANDS     0x26b0c

/* gamma_curves: 5 curves of 4096 u32. The blend runs on the stored curves and the result is decimated afterwards; that order is the vendor's and is not interchangeable. */
#define AR_ISP_GAMMA_BLOB_CURVES    0x5
#define AR_ISP_GAMMA_BLOB_STRIDE    0x4000
#define AR_ISP_GAMMA_BLOB_OFFSET    0x26b90

/* cm_header */
#define AR_ISP_CM_HDR_INTERP        0x4
#define AR_ISP_CM_HDR_AEC_COUNT     0x8
#define AR_ISP_CM_HDR_CT_COUNT      0xc
#define AR_ISP_CM_HEADER            0x89cfc

/* cm_aec_axis: the AEC abscissa cm's rows are selected on. Trigger-scalar axis, not the gain axis. */
#define AR_ISP_CM_AEC_ROWS          0x5
#define AR_ISP_CM_AEC_AXIS          0x89d10

/* wb: 5 AEC rows by 7 CT columns, cells of {gain f32, angle f32}. Static on this unit: the shipped tuning gates AWB off. */
#define AR_ISP_CM_TABLE             0x89d70

/* lnr_header */
#define AR_ISP_LNR_HDR_COUNT        0x8
#define AR_ISP_LNR_HDR_SELECT       0xc
#define AR_ISP_LNR_BLOB_HEADER      0x89e88

/* lnr_bands */
#define AR_ISP_LNR_BLOB_BANDS       0x89e98

/* lnr_payload: the two curve runs sit at fixed displacements inside each record */
#define AR_ISP_LNR_BANDS            0xb
#define AR_ISP_LNR_CURVE_OFF_LOW    0x110
#define AR_ISP_LNR_CURVE_OFF_HIGH   0x228
#define AR_ISP_LNR_BLOB_STRIDE      0x428
#define AR_ISP_LNR_BLOB_PAYLOAD     0x89f18

/* cnf_statics: twelve words feeding the six static cnf registers at ISP 0x3c8c..0x3ca0. Each register takes bits 10:0 from a lo word and the field at bit 11 from a hi word; the wide and narrow runs differ only in how many of the hi bits the register owns. Array literals in ar-isp-cnf.h, not defines. */
#define AR_ISP_CNF_STATIC_BLOB      0x8e1a8

/* cnf_bands */
#define AR_ISP_CNF_BLOB_BANDS       0x8e1dc

/* cnf_payload */
#define AR_ISP_CNF_BANDS            0xb
#define AR_ISP_CNF_BLOB_STRIDE      0x80c
#define AR_ISP_CNF_BLOB_PAYLOAD     0x8e25c

/* de3d_header */
#define AR_ISP_DE3D_HDR_COUNT       0x8
#define AR_ISP_DE3D_HDR_SELECT      0xc
#define AR_ISP_DE3D_BLOB_HEADER     0x9631c

/* de3d_bands */
#define AR_ISP_DE3D_BLOB_BANDS      0x9632c

/* de3d_payload */
#define AR_ISP_DE3D_BANDS           0xc
#define AR_ISP_DE3D_CURVE_OFF       0xe0
#define AR_ISP_DE3D_BLOB_STRIDE     0x2f8
#define AR_ISP_DE3D_BLOB_PAYLOAD    0x963ac

/* cm2_header: the interp word at 0xa1308 is what blob-coverage called the cm2 interpolate gate */
#define AR_ISP_CM2_HDR_INTERP       0x4
#define AR_ISP_CM2_HDR_AEC_COUNT    0x8
#define AR_ISP_CM2_HDR_CT_COUNT     0xc
#define AR_ISP_CM2_HEADER           0xa1304

/* cm2_aec_axis: cm2's AEC abscissa, the same trigger-scalar axis cm uses */
#define AR_ISP_CM2_AEC_ROWS         0x5
#define AR_ISP_CM2_AEC_AXIS         0xa1318

/* cm2_clamp: clamp bounds, 5 AEC rows by 7 CT columns of 24 bytes */
#define AR_ISP_CM2_TABLE            0xa1378

#endif /* AR_ISP_BLOB_H */
