/* SPDX-License-Identifier: GPL-2.0 */
/* Generated by kernel/scripts/isp/gen-rgb2yuv.py. Do not edit. */
/*
 * The colour-space matrices the vendor library carries, packed for the
 * rgb2yuv bank.
 *
 * isp_rgb2yuv_set_csc selects one of these four and a writer at 0x19e318
 * packs it as sign-magnitude Q10: magnitude |coeff| * 1024 truncated, bit 15
 * the sign. The shipped bank is BT.601 full range and reproduces bit-exactly
 * against a streaming-vendor capture, which is what gen-rgb2yuv.py --check
 * asserts.
 *
 * Full range puts black at 0 and white at 255; limited range puts them at 16
 * and 235. Changing which matrix is applied is the levels lever for the whole
 * YUV path, so the alternatives are carried rather than dropped.
 */

#ifndef AR_ISP_RGB2YUV_H
#define AR_ISP_RGB2YUV_H

#define AR_ISP_RGB2YUV_BANK		0x3c00
#define AR_ISP_RGB2YUV_REGS		6

struct ar_isp_csc {
	const char *name;
	u32 regs[6];
};

static const struct ar_isp_csc ar_isp_csc_matrices[] = {
	/* +0.299 +0.587 +0.114 -0.169 -0.331 +0.500 +0.500 -0.419 -0.081 */
	{ "bt601_full", { 0x02590132, 0x00000074, 0x815280ad, 0x02000200, 0x81ad0200, 0x02008052 } },

  /* +0.213 +0.715 +0.072 -0.117 -0.394 +0.511 +0.511 -0.464 -0.047 */
	{ "bt709_full", { 0x02dc00da, 0x00000049, 0x81938077, 0x020b020b, 0x81db020b, 0x020b8030 } },

  /* +0.257 +0.504 +0.098 -0.148 -0.291 +0.439 +0.439 -0.368 -0.071 */
	{ "bt601_limited", { 0x02040107, 0x00000064, 0x81298097, 0x01c101c1, 0x817801c1, 0x01c18048 } },

  /* +0.183 +0.614 +0.062 -0.101 -0.338 +0.439 +0.439 -0.399 -0.040 */
	{ "bt709_limited", { 0x027400bb, 0x0000003f, 0x815a8067, 0x01c101c1, 0x819801c1, 0x01c18028 } },
};

/* The matrix measured on the streaming vendor. */
#define AR_ISP_CSC_DEFAULT		0

#endif /* AR_ISP_RGB2YUV_H */
